development:
  adapter: postgresql
  database: etudelegendre_dev
  encoding: utf8
  username: postgres
  password: sharemyspot
  host: localhost
test:
  adapter: postgresql
  database: etudelegendre_test
  encoding: utf8
  username: postgres
  password: sharemyspot
  host: localhost
production:
  adapter: postgresql
  database: etudelegendre_prod
  encoding: utf8
  username: postgres
  password: sharemyspot
  host: localhost
