# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
#plugins:
#  -paste
#  - table
#  - fullscreen
mode: textareas
theme: "advanced"
theme_advanced_toolbar_location: "top"
theme_advanced_buttons1: "bold,italic,underline,|,justifyleft,justifycenter,justifyright,|,bullist,numlist,|,outdent,indent,|,undo,redo"
theme_advanced_buttons2: ""
theme_advanced_buttons3: ""
theme_advanced_resizing : true
paste_text_sticky:true
paste_auto_cleanup_on_paste : true
paste_remove_styles: true
paste_remove_styles_if_webkit: true
paste_strip_class_attributes: true